import {
  BHUPALI,
  BHAIRAV,
  BHAIRAVI,
  BLUES,
  HARMONIC_MINOR,
  KAFI,
  KHAMAJ,
  LOCRIAN,
  MAJOR,
  MALKAUNS,
  MELODIC_MINOR,
  MINOR_PENT,
  NATURAL_MINOR,
  PHRYG_DOM,
  YAMAN,
} from "./theory.ts";

export type ScaleDef = {
  id: string;
  name: string;
  aka: string;
  family: string;
  steps: number[];
  phrase: number[];
  tell: string;
  example: string;
  rule: string;
  avoid: string;
  guitar: string;
};

export const SCALES: ScaleDef[] = [
  {
    id: "major",
    name: "Major",
    aka: "Ionian",
    family: "Modes",
    steps: MAJOR,
    phrase: [0, 2, 4, 5, 7, 4, 2, 0],
    tell: "Bright 3rd (4 frets) and a 7th that leans up into home (11 frets).",
    example: "Happy birthday, Let It Be, most campfire songs. In C the letters are C D E F G A B — the same walk as the open C, G, and D shapes.",
    rule: "Walk 2 2 1 2 2 2 1 frets. In C: C D E F G A B. Open G, C, D, A, and E all use this walk.",
    avoid: "Nothing inside the scale is forbidden. It goes pale if you never let the 7th resolve.",
    guitar: "Open G, C, D, A, E. The major-scale box you already half-know is this.",
  },
  {
    id: "lydian",
    name: "Lydian",
    aka: "Raised 4th",
    family: "Modes",
    steps: YAMAN,
    phrase: [0, 2, 4, 6, 7, 6, 4, 2],
    tell: "The 4th is one fret higher than usual. Six frets above home.",
    example: "Like a major scale with one raised stair. In C, F becomes F#. The face is still bright, but a little dreamy.",
    rule: "Major scale with #4 instead of 4. In C: C D E F# G A B. Pass F; do not camp on it.",
    avoid: "Do not rest on the natural 4th. An F chord in C plants the one note Lydian keeps moving past.",
    guitar: "In C, D major contains F#, the raised 4th. C, D, and G sketch a bed. Touch F# and do not camp on F.",
  },
  {
    id: "mixolydian",
    name: "Mixolydian",
    aka: "Flat 7th",
    family: "Modes",
    steps: KHAMAJ,
    phrase: [0, 4, 7, 10, 7, 5, 4, 0],
    tell: "Bright 3rd, but the 7th is one fret lower than major (10 frets, not 11).",
    example: "Like a major song that leaves the front door open. In D, C# becomes C. Sweet Child, lots of folk, and some film guitar lessons live here.",
    rule: "Major scale with b7. In C: C D E F G A Bb. Keep the bright 3rd. If the 3rd goes sad, you left Mixolydian.",
    avoid: "Do not turn it into natural minor. Keep the major 3rd. The flat 7th against a major home is the color.",
    guitar: "Play a major chord on home, then the fret one below the major 7th. In D that note is C. D, G, and A still work. The melody supplies the C.",
  },
  {
    id: "dorian",
    name: "Dorian",
    aka: "Minor with a major 6th",
    family: "Modes",
    steps: KAFI,
    phrase: [0, 2, 3, 5, 7, 9, 7, 5],
    tell: "Sad 3rd (3 frets), but a bright 6th (9 frets). That 6th is the tell versus ordinary minor.",
    example: "Like minor clothing with a smile in the 6th. In A, natural minor wants F. Dorian wants F#.",
    rule: "Only flatten the 3rd and the 7th. In A: A B C D E F# G.",
    avoid: "If you also flatten the 6th, you walked into natural minor. Pop songs do this on purpose. Notice when they do.",
    guitar: "Minor chord on home. The 6th of the scale is major. Santana, plenty of funk, and a lot of folk live here.",
  },
  {
    id: "minor",
    name: "Natural minor",
    aka: "Aeolian",
    family: "Modes",
    steps: NATURAL_MINOR,
    phrase: [0, 3, 7, 8, 7, 5, 3, 0],
    tell: "Sad 3rd and sad 6th. The default “sad pop” sound.",
    example: "A minor and C major are the same seven letters. Home moved, like the same house with a different front door. In A: A B C D E F G.",
    rule: "Flatten 3, 6, and 7. Am F C G is this collection as chords.",
    avoid: "Do not assume every minor song is this. Test the 6th. F# in A minor is Dorian. F in A minor is this.",
    guitar: "Am, Dm, Em, F, C, G are the usual open set. The vi of C major is this home.",
  },
  {
    id: "phrygian",
    name: "Phrygian",
    aka: "Flat 2nd",
    family: "Modes",
    steps: BHAIRAVI,
    phrase: [0, 1, 3, 5, 3, 1, 0],
    tell: "The 2nd is only one fret above home. That tiny step is the whole mood.",
    example: "Like landing on the stair right above the floor, not two stairs up. In A, B becomes Bb.",
    rule: "Natural minor plus a flat 2nd. In E: E F G A B C D.",
    avoid: "Metal and flamenco sit here. Film songs often add extra notes. The home still feels like a flat 2nd and a minor 3rd.",
    guitar: "From a natural-minor shape, move the 2nd down one fret. In A minor the usual B becomes Bb.",
  },
  {
    id: "locrian",
    name: "Locrian",
    aka: "Diminished home",
    family: "Modes",
    steps: LOCRIAN,
    phrase: [0, 1, 3, 6, 3, 1, 0],
    tell: "Flat 2nd and a 5th that is one fret low. Home itself is unstable.",
    example: "Almost no song lives here as home. You meet it as the last chord of C major (B dim), which wants to run back to C.",
    rule: "In B: B C D E F G A. Check the 5th: 6 frets up, not 7.",
    avoid: "Do not force a song into Locrian because a riff used a b5. Power chords hide the 3rd. Check the 5th.",
    guitar: "B dim in C major is this. One fret of the 5th is the tell: 6 frets up, not 7.",
  },
  {
    id: "harmonic-minor",
    name: "Harmonic minor",
    aka: "Raised 7th in minor",
    family: "Minor color",
    steps: HARMONIC_MINOR,
    phrase: [0, 3, 7, 11, 12, 11, 7, 3],
    tell: "Sad 3rd, but the 7th is raised so V becomes a bright chord.",
    example: "Why Am songs use E or E7, not Em. In A, G becomes G#, and that G# lives inside E major.",
    rule: "Natural minor with a raised 7th. In A: A B C D E F G#.",
    avoid: "The three-fret jump is the flavor. Filling it with a G natural turns it back into pop minor.",
    guitar: "Am songs that use E or E7 instead of Em are borrowing this. The V chord is the proof.",
  },
  {
    id: "melodic-minor",
    name: "Melodic minor",
    aka: "Jazz minor, ascending",
    family: "Minor color",
    steps: MELODIC_MINOR,
    phrase: [0, 2, 3, 5, 7, 9, 11, 12],
    tell: "Sad 3rd, but 6th and 7th are both bright.",
    example: "Think of Dorian with the door closed (raised 7th), or major with a sad 3rd. Jazz uses this more than campfire pop.",
    rule: "In A: A B C D E F# G#. Dorian’s 7th is G. This 7th is G#.",
    avoid: "Do not confuse it with Dorian. Dorian's 7th is flat. This 7th is major.",
    guitar: "Useful over minor-major chords and over a V7 that will resolve to minor. A rarer everyday pop sound.",
  },
  {
    id: "phryg-dom",
    name: "Phrygian dominant",
    aka: "Spanish / Hijaz",
    family: "Minor color",
    steps: PHRYG_DOM,
    phrase: [0, 1, 4, 5, 7, 5, 4, 1],
    tell: "Tiny 2nd (1 fret) plus a bright 3rd (4 frets). A jump over an empty stair.",
    example: "Flamenco, some metal, film “danger” cues. In E: E F G# — skip F# on purpose.",
    rule: "In E: E F G# A B C D. Do not fill the gap between F and G#.",
    avoid: "Do not fill the gap between b2 and 3. That empty fret is the scale.",
    guitar: "E major shape, then the fret immediately above E as a melody note. The open F on the low E string, if home is E, is the tell.",
  },
  {
    id: "byzantine",
    name: "Byzantine",
    aka: "Double harmonic major",
    family: "Minor color",
    steps: BHAIRAV,
    phrase: [0, 1, 4, 5, 7, 8, 11, 12],
    tell: "Two empty stairs: tiny 2nd, then a jump to a bright 3rd, then another jump near the top.",
    example: "Old, wide, serious. In C: C Db E F G Ab B. Rare as a pop home, unmistakable as a color.",
    rule: "Like Phrygian dominant with a bright 7th instead of a flat 7th.",
    avoid: "Do not fill either gap. Fret 2 and fret 9 are the empty rooms.",
    guitar: "From home: one fret up, skip to four, then the rest of a harmonic-major world. Rare as a pop tonic, unmistakable as a color.",
  },
  {
    id: "major-pent",
    name: "Major pentatonic",
    aka: "1 2 3 5 6",
    family: "Five notes",
    steps: BHUPALI,
    phrase: [0, 2, 4, 7, 9, 7, 4, 2, 0],
    tell: "Five notes. No 4th, no 7th — the two clash notes of major are simply missing.",
    example: "Folk, country, singable hooks. In C: C D E G A. Same dots as A minor pentatonic. Home moved three frets.",
    rule: "In C: C D E G A. Relative of A minor pentatonic.",
    avoid: "Do not sit on the 4th or 7th. In G, a C chord brings the 4th and a D chord brings the 7th. G and Em stay inside.",
    guitar: "Same frets as the minor pentatonic three frets lower. Index on fret 5 of low E is A minor pent. Call C home and it is this.",
  },
  {
    id: "minor-pent",
    name: "Minor pentatonic",
    aka: "The box",
    family: "Five notes",
    steps: MINOR_PENT,
    phrase: [0, 3, 5, 7, 10, 7, 5, 3, 0],
    tell: "The first rock box: 1, sad 3rd, 4, 5, sad 7th.",
    example: "Index on low E fret 5 is A minor pentatonic: A C D E G. Call C home on the same dots and it is major pentatonic.",
    rule: "In A: A C D E G. Not every minor song. If you need F or F# in A, you left the box.",
    avoid: "It is not every minor. No 2nd, no 6th. If the song needs F or F# in A, you have left the box.",
    guitar: "Five positions up the neck. Day 9 and the gym will make the first box automatic. Then connect it.",
  },
  {
    id: "blues",
    name: "Blues",
    aka: "Minor pentatonic plus b5",
    family: "Five notes",
    steps: BLUES,
    phrase: [0, 3, 5, 6, 7, 10, 7, 6, 5],
    tell: "Minor pentatonic plus one extra fret between 4 and 5.",
    example: "The “blue” note. In A that extra letter is Eb. Bend it up toward E. Judge the landing, not the journey.",
    rule: "In A: A C D Eb E G. Parking on Eb without moving is a joke, not a phrase.",
    avoid: "Parking on the b5 without moving it is a joke, not a phrase. It is a passing fret.",
    guitar: "Same box as minor pentatonic. Add the fret between 4 and 5 on each string that has those two.",
  },
  {
    id: "malkauns-pent",
    name: "Minor pentatonic, no 5",
    aka: "1 b3 4 b6 b7",
    family: "Five notes",
    steps: MALKAUNS,
    phrase: [0, 3, 5, 8, 10, 8, 5, 3, 0],
    tell: "Like the usual minor box, but the 5th moved up one fret. No 5th, no 2nd.",
    example: "Take A C D E G and move E up to F. Heavier, slower. Easy to confuse with the box you already know.",
    rule: "In C: C Eb F Ab Bb. Playing the old 5th turns this back into ordinary minor pentatonic.",
    avoid: "Your minor-pentatonic box includes the 5th. Playing the old 5th turns this back into ordinary minor pentatonic.",
    guitar: "Take the minor pentatonic and shift the 5th up one fret.",
  },
];

export function scaleById(id: string): ScaleDef | undefined {
  return SCALES.find((scale) => scale.id === id);
}
