import {
  BHUPALI,
  BHAIRAV,
  BHAIRAVI,
  BLUES,
  HARMONIC_MINOR,
  KAFI,
  KHAMAJ,
  LOCRIAN,
  MAJOR,
  MALKAUNS,
  MELODIC_MINOR,
  MINOR_PENT,
  NATURAL_MINOR,
  PHRYG_DOM,
  YAMAN,
} from "./theory.ts";

export type ScaleDef = {
  id: string;
  name: string;
  aka: string;
  family: string;
  steps: number[];
  phrase: number[];
  tell: string;
  rule: string;
  avoid: string;
  guitar: string;
};

export const SCALES: ScaleDef[] = [
  {
    id: "major",
    name: "Major",
    aka: "Ionian",
    family: "Modes",
    steps: MAJOR,
    phrase: [0, 2, 4, 5, 7, 4, 2, 0],
    tell: "Major 3rd (4 frets) and major 7th (11 frets). The 7th leans up into home.",
    rule: "2 2 1 2 2 2 1. In C: C D E F G A B. This is the parent of open G, C, D, A, and E. The 4th is a normal perfect 4th, five frets up.",
    avoid: "Nothing inside the scale is forbidden. It goes pale if you never let the 7th resolve.",
    guitar: "Open G, C, D, A, E. The major-scale box you already half-know is this.",
  },
  {
    id: "lydian",
    name: "Lydian",
    aka: "Raised 4th",
    family: "Modes",
    steps: YAMAN,
    phrase: [0, 2, 4, 6, 7, 6, 4, 2],
    tell: "The 4th is raised one fret. Six frets above home, a tritone. That one note is the whole identity.",
    rule: "Major scale with #4 instead of 4. In C: C D E F# G A B. The natural 4th (F) is the note you pass, not the note you sit on.",
    avoid: "Do not rest on the natural 4th. An F chord in C plants the one note Lydian keeps moving past.",
    guitar: "In C, D major contains F#, the raised 4th. C, D, and G sketch a bed. Touch F# and do not camp on F.",
  },
  {
    id: "mixolydian",
    name: "Mixolydian",
    aka: "Flat 7th",
    family: "Modes",
    steps: KHAMAJ,
    phrase: [0, 4, 7, 10, 7, 5, 4, 0],
    tell: "Major 3rd, flat 7th. Ten frets above home. A major key with the door left open.",
    rule: "Major scale with b7. In C: C D E F G A Bb. The 3rd stays major. If the 3rd goes minor, you have left Mixolydian.",
    avoid: "Do not turn it into natural minor. Keep the major 3rd. The flat 7th against a major home is the color.",
    guitar: "Play a major chord on home, then the fret one below the major 7th. In D that note is C. D, G, and A still work. The melody supplies the C.",
  },
  {
    id: "dorian",
    name: "Dorian",
    aka: "Minor with a major 6th",
    family: "Modes",
    steps: KAFI,
    phrase: [0, 2, 3, 5, 7, 9, 7, 5],
    tell: "Minor 3rd, major 6th. The 6th is the note that separates Dorian from natural minor.",
    rule: "b3 and b7 only. 2nd and 6th stay major. In D: D E F G A B C. In A: A B C D E F# G. Natural minor in A would have used F, not F#.",
    avoid: "If you also flatten the 6th, you walked into natural minor. Pop songs do this on purpose. Notice when they do.",
    guitar: "Minor chord on home. The 6th of the scale is major. Santana, plenty of funk, and a lot of folk live here.",
  },
  {
    id: "minor",
    name: "Natural minor",
    aka: "Aeolian",
    family: "Modes",
    steps: NATURAL_MINOR,
    phrase: [0, 3, 7, 8, 7, 5, 3, 0],
    tell: "Minor 3rd and minor 6th. The sad-pop default. Relative of a major key three frets up.",
    rule: "b3, b6, b7. In A: A B C D E F G. Same pitches as C major. Home moved. A minor loop Am F C G is this collection as chords.",
    avoid: "Do not assume every minor song is this. Test the 6th. F# in A minor is Dorian. F in A minor is this.",
    guitar: "Am, Dm, Em, F, C, G are the usual open set. The vi of C major is this home.",
  },
  {
    id: "phrygian",
    name: "Phrygian",
    aka: "Flat 2nd",
    family: "Modes",
    steps: BHAIRAVI,
    phrase: [0, 1, 3, 5, 3, 1, 0],
    tell: "The 2nd is one fret above home. That half step is the whole mood.",
    rule: "b2, b3, b6, b7. In E: E F G A B C D. In A: A Bb C D E F G. Compared with natural minor, only the 2nd moved down one fret.",
    avoid: "Metal and flamenco sit here. Film songs often add extra notes. The home still feels like a flat 2nd and a minor 3rd.",
    guitar: "From a natural-minor shape, move the 2nd down one fret. In A minor the usual B becomes Bb.",
  },
  {
    id: "locrian",
    name: "Locrian",
    aka: "Diminished home",
    family: "Modes",
    steps: LOCRIAN,
    phrase: [0, 1, 3, 6, 3, 1, 0],
    tell: "Flat 2nd and flat 5th. The home triad is diminished. Almost no song lives here as a tonic.",
    rule: "1 b2 b3 4 b5 b6 b7. In B: B C D E F G A. You meet it as vii° of C major, not as a key you camp in.",
    avoid: "Do not force a song into Locrian because a riff used a b5. Power chords hide the 3rd. Check the 5th.",
    guitar: "B dim in C major is this. One fret of the 5th is the tell: 6 frets up, not 7.",
  },
  {
    id: "harmonic-minor",
    name: "Harmonic minor",
    aka: "Raised 7th in minor",
    family: "Minor color",
    steps: HARMONIC_MINOR,
    phrase: [0, 3, 7, 11, 12, 11, 7, 3],
    tell: "Minor 3rd, major 7th. The gap from b6 to 7 is three frets. That is why V becomes major in a minor key.",
    rule: "Natural minor with a raised 7th. In A: A B C D E F G#. The E major or E7 chord contains G#, which is that raised 7th.",
    avoid: "The three-fret jump is the flavor. Filling it with a G natural turns it back into pop minor.",
    guitar: "Am songs that use E or E7 instead of Em are borrowing this. The V chord is the proof.",
  },
  {
    id: "melodic-minor",
    name: "Melodic minor",
    aka: "Jazz minor, ascending",
    family: "Minor color",
    steps: MELODIC_MINOR,
    phrase: [0, 2, 3, 5, 7, 9, 11, 12],
    tell: "Minor 3rd, major 6th, major 7th. Dorian with a raised 7th, or major with a flat 3rd.",
    rule: "Classical school: raise 6 and 7 going up, natural minor coming down. Jazz mostly keeps this form both ways. In A: A B C D E F# G#.",
    avoid: "Do not confuse it with Dorian. Dorian's 7th is flat. This 7th is major.",
    guitar: "Useful over minor-major chords and over a V7 that will resolve to minor. A rarer everyday pop sound.",
  },
  {
    id: "phryg-dom",
    name: "Phrygian dominant",
    aka: "Spanish / Hijaz",
    family: "Minor color",
    steps: PHRYG_DOM,
    phrase: [0, 1, 4, 5, 7, 5, 4, 1],
    tell: "Flat 2nd and major 3rd. The jump from fret 1 to fret 4 is an augmented 2nd. Flamenco, metal, and a lot of film villain cues.",
    rule: "5th mode of harmonic minor. In E: E F G# A B C D. In A: A Bb C# D E F G. Major home, exotic 2nd.",
    avoid: "Do not fill the gap between b2 and 3. That empty fret is the scale.",
    guitar: "E major shape, then the fret immediately above E as a melody note. The open F on the low E string, if home is E, is the tell.",
  },
  {
    id: "byzantine",
    name: "Byzantine",
    aka: "Double harmonic major",
    family: "Minor color",
    steps: BHAIRAV,
    phrase: [0, 1, 4, 5, 7, 8, 11, 12],
    tell: "Flat 2nd, major 3rd, flat 6th, major 7th. Two augmented-2nd gaps.",
    rule: "In C: C Db E F G Ab B. Like Phrygian dominant with a major 7th instead of a flat 7th. Serious, wide, old.",
    avoid: "Do not fill either gap. Fret 2 and fret 9 are the empty rooms.",
    guitar: "From home: one fret up, skip to four, then the rest of a harmonic-major world. Rare as a pop tonic, unmistakable as a color.",
  },
  {
    id: "major-pent",
    name: "Major pentatonic",
    aka: "1 2 3 5 6",
    family: "Five notes",
    steps: BHUPALI,
    phrase: [0, 2, 4, 7, 9, 7, 4, 2, 0],
    tell: "No 4th, no 7th. Five notes. Folk, country, and a huge share of singable hooks.",
    rule: "In C: C D E G A. Relative of A minor pentatonic. The missing 4th and 7th are the clash notes of the major scale, so this box is safe.",
    avoid: "Do not sit on the 4th or 7th. In G, a C chord brings the 4th and a D chord brings the 7th. G and Em stay inside.",
    guitar: "Same frets as the minor pentatonic three frets lower. Index on fret 5 of low E is A minor pent. Call C home and it is this.",
  },
  {
    id: "minor-pent",
    name: "Minor pentatonic",
    aka: "The box",
    family: "Five notes",
    steps: MINOR_PENT,
    phrase: [0, 3, 5, 7, 10, 7, 5, 3, 0],
    tell: "1 b3 4 5 b7. The rock and blues box. Relative of the major pentatonic three frets higher.",
    rule: "In A: A C D E G. Start with the index on low E fret 5. This is the shape most guitarists learn first.",
    avoid: "It is not every minor. No 2nd, no 6th. If the song needs F or F# in A, you have left the box.",
    guitar: "Five positions up the neck. Day 9 and the gym will make the first box automatic. Then connect it.",
  },
  {
    id: "blues",
    name: "Blues",
    aka: "Minor pentatonic plus b5",
    family: "Five notes",
    steps: BLUES,
    phrase: [0, 3, 5, 6, 7, 10, 7, 6, 5],
    tell: "The extra note sits between 4 and 5. That fret is the blues note.",
    rule: "1 b3 4 b5 5 b7. In A: A C D Eb E G. Bend the b5 up toward the 5th. The mic will call the bend 'out' in the middle. Judge the landing.",
    avoid: "Parking on the b5 without moving it is a joke, not a phrase. It is a passing fret.",
    guitar: "Same box as minor pentatonic. Add the fret between 4 and 5 on each string that has those two.",
  },
  {
    id: "malkauns-pent",
    name: "Minor pentatonic, no 5",
    aka: "1 b3 4 b6 b7",
    family: "Five notes",
    steps: MALKAUNS,
    phrase: [0, 3, 5, 8, 10, 8, 5, 3, 0],
    tell: "Compared with the usual minor box, the 5th moved up one fret to a minor 6th. No 2nd, no 5th.",
    rule: "In C: C Eb F Ab Bb. Heavy, slow, and easy to confuse with the box you already know.",
    avoid: "Your minor-pentatonic box includes the 5th. Playing the old 5th turns this back into ordinary minor pentatonic.",
    guitar: "Take the minor pentatonic and shift the 5th up one fret.",
  },
];

export function scaleById(id: string): ScaleDef | undefined {
  return SCALES.find((scale) => scale.id === id);
}
